---
title: "Tidy Tuesday: Numbat observations in Australia"
date: 3/06/2023
author:
  - name: Deepsha Menghani 
    url: https://github.com/deepshamenghani
title-block-banner: true
format:
  html:
    theme: flatly
    code-fold: false
    code-tools: true
    toc: false
    number-sections: true
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  eval = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.height = 7
)
```

In this post, I will analyse the [#TidyTuesday](https://github.com/rfordatascience/tidytuesday/tree/master/) Australia Numbats dataset. The data this week comes from the [Atlas of Living Australia](https://www.ala.org.au/). Thanks to Di Cook for [preparing this week's dataset](https://github.com/numbats/numbats-tidytuesday)!

::: callout-tip
You can find my github code repository [here](https://github.com/deepshamenghani/tidytuesday/tree/master/2023/week10_numbats_australia).
:::

## Load libraries

```{r install packages, message=FALSE, warning=FALSE, include=TRUE, paged.print=FALSE, eval=TRUE, echo=TRUE}

# For loading Tidy Tuesday data
library(tidytuesdayR)

# EDA
library(tidyverse)
library(DT)

# Plotting
library(highcharter)

```

## Load data

```{r}
numbats <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-03-07/numbats.csv')

numbats %>% 
  head()
```


```{r}

numbats %>% 
  count(year)
```
```{r}
numbats_edited <- numbats %>% 
  filter(year >= 2000) %>% 
  count(dataResourceName, year) %>% 
  complete(dataResourceName, year = seq(2000,2020,by=1)) %>% 
  replace_na(list(n=0)) 

# Create the initial column plot data
numbats_column <- numbats_edited %>% 
  group_by(name = dataResourceName) %>% 
  summarise(n = sum(n)) %>% 
  ungroup() %>% 
  mutate(drilldown = tolower(name)) %>% 
  arrange(desc(n)) %>% 
  head(5) %>% 
  tibble()

# Create the yearly drilldown data
numbats_year <- numbats_edited %>% 
  group_by(year) %>% 
  summarise(n = sum(n)) %>% 
  ungroup() 

# Create ids to connect layers of plot
idlist <- numbats_column$name

yearlyview <- idlist %>% map(~ numbats_edited %>% 
                               filter(dataResourceName == .x) %>% select(year, n))

dflist <- yearlyview %>% map(~ list_parse2(.x))

listall <- c(1:5) %>% map(~ list(
  id = tolower(idlist[[.x]]),
  data = dflist[[.x]]
))

numbat_observations <-   highchart() %>%
  hc_title(text = "Numbat observations by Data Resource",
           style = list(fontWeight = "bold", fontSize = "20px"),
           align = "center") %>% 
  hc_subtitle(text = "Top 5 by count from year 2000 onward") %>% 
  hc_caption(text = "Click on bar to drilldown for yearly view") %>% 
  hc_xAxis(type = "category") %>%
  hc_legend(enabled = FALSE) %>%
  hc_plotOptions(
    series = list(
      boderWidth = 0,
      dataLabels = list(
        enabled = TRUE,
        style = list(fontSize = 15, textOutline = "none")
      )
    )
  ) %>%
  hc_add_series(
    data = numbats_column,
    type = "column",
    hcaes(name = name, y = n),
    name = "observations",
    color = "#008080"
  ) %>% 
  hc_drilldown(
    allowPointDrilldown = TRUE,
    series = listall
  ) 
```

```{r}
numbat_observations
```


